# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0.0'

gem 'httparty', '~> 0.21'
gem 'nokogiri', '~> 1.15'
gem 'rake', '~> 13.0'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-rspec', '~> 2.20'
  gem 'webmock', '~> 3.18'
end

group :test do
  gem 'simplecov', require: false
  gem 'vcr', '~> 6.1'
end
