# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0.0'

gem 'rake', '~> 13.0'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-rspec', '~> 2.20'
end

group :test do
  gem 'simplecov', require: false
end
