# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0'
gem 'sinatra-activerecord', '~> 2.0'
gem 'activerecord', '~> 7.0'
gem 'sqlite3', '~> 1.6'
gem 'bcrypt', '~> 3.1'
gem 'jwt', '~> 2.7'
gem 'puma', '~> 6.0'
gem 'rackup', '~> 2.0'
gem 'rack-cors', '~> 2.0'
