# frozen_string_literal: true

source 'https://rubygems.org'

# Web framework
gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'

# Web server
gem 'puma', '~> 6.0'
gem 'rackup', '~> 2.1'

# Database
gem 'sequel', '~> 5.0'
gem 'sqlite3', '~> 1.6'
